// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    var $nav, navPos;
    $nav = $('.news-category-pc');
    navPos = $nav.offset().top - 20;
    return $(window).on('scroll', function() {
      if ($(this).scrollTop() > navPos) {
        return $nav.addClass('fixed');
      } else {
        return $nav.removeClass('fixed');
      }
    });
  });

}).call(this);
