
;(function(){$.fn.extend({aemProtectImage:function(t){var e,n,o,i;return o={disableContextmenu:!1,blankImg:"/img/blank.gif",zIndex:1e3},o=$.extend(o,t),e=new Image,e.src=o.blankImg,n=e.cloneNode(),$(e).addClass("blank-img"),o.disableContextmenu===!0&&$(window).on("contextmenu",function(){return!1}),i=function(t){var e,i,a,s;return e=$(t),s=e.offset(),a=e.width(),i=e.height(),$(n.cloneNode()).attr({width:a,height:i}).css({position:"absolute",top:s.top,left:s.left,zIndex:o.zIndex,width:a,height:i}).appendTo("body")},this.each(function(){var t,n,o;return n=$(this),n.on("contextmenu",function(){return!1}),"img"===this.tagName.toLowerCase()?(i(this),!0):(o=n.css("position"),"absolute"!==o&&"relative"!==o&&n.css("position","relative"),t=$(e).clone().css({position:"absolute",top:0,left:0,width:"100%",height:"100%"}),n.append(t))})}})}).call(this);
;(function(){var t;t=function(t){return window.console?console.log(t):void 0},$.fn.extend({aemTab:function(t){var s,e,i;return i={titlesClass:"js-tab-titles",titleClass:"js-tab-title",itemClass:"js-tab-item",activeClass:"active",dataProperty:"data-target",touchAction:!1},i=$.extend(i,t),e="click",i.touchAction===!0&&(e="touchend"),s=function(t,s,e){return setTimeout(function(){var a;return a=i.activeClass,t.removeClass(a).eq(e).addClass(a),s.hide().removeClass(a).eq(e).show().addClass(a)},1)},$(this).each(function(){var t,e,a,n,l;return t=$(this),n=t.find("."+i.titlesClass),a=n.find("."+i.titleClass),e=t.find("."+i.itemClass).hide(),l=!1,n.find("."+i.titleClass).each(function(n){return t=$(this),t.hasClass(i.activeClass)?(s(a,e,n),l=!0,!1):void 0}),l===!1&&s(a,e,0),n.on("click","."+i.titleClass,function(){return s(a,e,a.index(this)),!1})})}})}).call(this);
;(function(){$.fn.extend({aemToTop:function(n){var e,o,i,l;return l={scrollPos:200},l=$.extend(l,n),e=this.hide(),o=!1,i=l.scrollPos,$win.on("scroll",function(){if($win.scrollTop()>i){if(o===!1)return e.fadeIn(),o=!0}else if(o===!0)return e.fadeOut(),o=!1})}})}).call(this);
;(function(){$.fn.extend({aemTouchUtil:function(t){var e;return e={touchClassName:"is-touch"},e=$.extend(e,t),this.each(function(){var t;return t=$(this),t.on("touchstart",function(){return t.addClass(e.touchClassName)}).on("touchmove",function(){return t.removeClass(e.touchClassName)}).on("touchend",function(){return t.removeClass(e.touchClassName)})})},aemTouch:function(t){var e,a;return a={touchClassName:"is-touch"},a=$.extend(a,t),e="function"==typeof a.callback,$(this).each(function(){var t,n,o,u;return t=$(this),n=!1,o=null,u=null,t.on("touchend touchstart touchmove click",function(c){var s,r;if(s=c.type,"click"===s){if(t.data("eventHandled")===!0)return t.data("eventHandled",!1),!1;if(e===!0)return a.callback(t,c),!1}if("touchstart"===s)return n=!1,r=c.originalEvent.touches,o=r[0].pageX,u=r[0].pageY,t.addClass(a.touchClassName),!0;if("touchmove"===s)return(Math.abs(c.originalEvent.touches[0].pageX-o)>12||Math.abs(c.originalEvent.touches[0].pageY-u)>12)&&(n=!0,t.removeClass(a.touchClassName)),!0;if("touchend"===c.type){if(n===!0)return n=!1,!1;if(t.removeClass(a.touchClassName),e===!0)return t.data("eventHandled",!0),a.callback(t,c),!1}})})}})}).call(this);
;(function(){var n,t;t=function(n){return window.console?console.log(n):void 0},n={setupMenuBtn:function(){var n,t;return n=$(".spmenu"),t=n.find(".spmenu__inner"),$("#menu-btn").aemTouch({callback:function(e){return e.toggleClass("active"),n.toggleClass("active"),t.slideToggle()}})},setupAccordion:function(){var n;return n=$(".accordion"),n.find("dt").aemTouch({callback:function(n){return n.next("dd").slideToggle()}}),n.find("dd:not(.open)").hide(),$(".accordion1 dd").css("display","none"),$(".accordion1 dt").click(function(){return $(this).toggleClass("open").next().slideToggle("fast")})},setupTab:function(){return $(".js-tab").aemTab()},setupGallery:function(){return $.fn.photoSwipe?$("#Gallery").find("a").photoSwipe():void 0},init:function(){return this.setupMenuBtn(),this.setupAccordion(),this.setupTab(),this.setupGallery(),this.load()},load:function(){return $(window).on("load",function(){return $(".js-protect, .protect").aemProtectImage({blankImg:"/images/blank.gif"})})}},$(function(){return n.init()})}).call(this);

$(function(){
$('.archives dd').hide();
$('.archives dt').on("click", function() {
$(this).next('.archives dd').slideToggle();
return false;
});
});